greeting.prefix = Hi

spring.datasource.url=jdbc:mysql://greetings.cfyufg0ce9mc.us-east-2.rds.amazonaws.com:3306/greetings
spring.datasource.username=admin
spring.datasource.password=mypassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# HTTPS Configuration
server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

# AWS Cognito JWT Configuration
# Replace these values with your Cognito User Pool details
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_02kLpiKw6
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-2.amazonaws.com/us-east-2_02kLpiKw6/.well-known/jwks.json